In [1]:
import numpy

In [2]:
array = numpy.array([10, 20, 30, 40])

In [8]:
array

array([10, 20, 30, 40])

In [4]:
type(array)

numpy.ndarray

In [25]:
matriz01 = numpy.array([[1, 2], [3, 4]])
matriz02 = numpy.array([[1, 2], [3, 4]])

In [18]:
matriz01

array([[1, 2],
       [3, 4]])

In [19]:
type(matriz01)

numpy.ndarray

In [20]:
matriz01[1][1]

4

In [21]:
matriz01[1, 1]

4

In [22]:
matriz01[1,:]

array([3, 4])

In [23]:
matriz01[:,0]

array([1, 3])

In [24]:
matriz01.transpose()

array([[1, 3],
       [2, 4]])

In [26]:
matriz01 + matriz02

array([[2, 4],
       [6, 8]])

In [27]:
matriz01 - matriz02

array([[0, 0],
       [0, 0]])

In [28]:
matriz01 * matriz02

array([[ 1,  4],
       [ 9, 16]])

In [29]:
matriz01 / matriz02

array([[ 1.,  1.],
       [ 1.,  1.]])

In [30]:
array.sum()

100

In [31]:
array.argmax()

3

In [32]:
array.argmin()

0